### ISSUE TITLE
[Feature Request] Different sizes

### ISSUE THREAD

**Issue by Jacinto27** [ripperhowls/Posys-Cursors-Improved-by-ripperhowls#2]
I loved posy for windows 10 and I love this version for windows 11, but now I have quite a small laptop and these cursors become hard to see. 

What I've done is used a large version of mouse skins online which are properly scaled, given that the windows mouse scaling feature is bad, and I'd preferred it if I could use this version instead. I know I might be asking too much but could it be possible to add additional pre-made sizes to these cursors? I'm 100% willing to contribute if it comes to it.

**Comment by ripperhowls** [comment]
Long time no see.
Sorry it's been a while since I've made last update...

Already started working on a version of the cursors for 125 & 175% scales
[The default scheme for 125\175% scales](https://github.com/ripperhowls/Posys-Cursors-Improved-by-ripperhowls/tree/171c42d3016b25ee9dfae362af246f67503db40d/Default%20for%20125%20%26%20175%25%20scales) is already uploaded, you can try it now! :)

Will finish the new update in the next couple days
