### ISSUE TITLE
Larger variants for 125% and 175% scaling

### ISSUE THREAD

**Issue by stamminator** [ripperhowls/Posys-Cursors-Improved-by-ripperhowls#3]
Posy's cursors some with slightly larger variants to correct for the lame Windows behavior of displaying the cursor too small at certain display scales like 125% and 175%. It would be great to have your improved versions of these cursors in that size. For now, our only option is to put up with a tiny cursor or go back to Posy's originals, but I like your designs much better.

**Comment by ripperhowls** [comment]
Long time no see.
Sorry it's been a while since I've made last update...

Already started working on a version of the cursors for 125 & 175% scales
[The default scheme for 125\175% scales](https://github.com/ripperhowls/Posys-Cursors-Improved-by-ripperhowls/tree/171c42d3016b25ee9dfae362af246f67503db40d/Default%20for%20125%20%26%20175%25%20scales) is already uploaded, you can try it now! :)

Will finish the new update in the next couple days. Thanks for using the cursors!

**Comment by stamminator** [comment]
Thank you!
